#!/bin/bash
# Script to help configure branch protection rules via GitHub CLI
# This script provides commands to set up branch protection for the main branch

OWNER="ChanchalSen09"
REPO="CodeMentor-AI"
BRANCH="main"

echo "================================================"
echo "Branch Protection Setup for CodeMentor-AI"
echo "================================================"
echo ""
echo "This script helps you configure branch protection rules."
echo "You need to have GitHub CLI (gh) installed and authenticated."
echo ""
echo "To apply basic branch protection to the '$BRANCH' branch, run:"
echo ""
echo "gh api repos/$OWNER/$REPO/branches/$BRANCH/protection \\"
echo "  --method PUT \\"
echo "  --field required_pull_request_reviews[required_approving_review_count]=1 \\"
echo "  --field required_pull_request_reviews[dismiss_stale_reviews]=true \\"
echo "  --field enforce_admins=false \\"
echo "  --field required_conversation_resolution=true \\"
echo "  --field restrictions=null \\"
echo "  --field required_status_checks=null \\"
echo "  --field allow_force_pushes[enabled]=false \\"
echo "  --field allow_deletions[enabled]=false"
echo ""
echo "================================================"
echo ""
echo "Or configure via GitHub Web UI:"
echo "1. Go to: https://github.com/$OWNER/$REPO/settings/branches"
echo "2. Click 'Add rule' under 'Branch protection rules'"
echo "3. Set branch name pattern: $BRANCH"
echo "4. Enable the following:"
echo "   ✓ Require a pull request before merging"
echo "   ✓ Require approvals (1 minimum)"
echo "   ✓ Dismiss stale pull request approvals when new commits are pushed"
echo "   ✓ Require conversation resolution before merging"
echo "   ✗ Do not allow force pushes"
echo "   ✗ Do not allow deletions"
echo "5. Click 'Create' or 'Save changes'"
echo ""
echo "================================================"
echo ""
echo "For more details, see: BRANCH_PROTECTION.md"
echo ""
